name: Send a message to slack

on:
  # uncomment the below two lines if you want to schedule a workflow
  # schedule:
    # - cron:  '0 4 * * 0'  # UTC times using POSIX cron syntax.
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2

      - name: install dependencies
        run: poetry install

      - name: Send message
        run:
          poetry run python send_message.py --slack_api_token ${{ secrets.SLACK_API_TOKEN }}


